### ISSUE TITLE
The ancient forgotten spell

### ISSUE THREAD

**Issue by Kruwed** [molnard/The-release-game-v2-0-4-1#25]
**📜 Preamble**

Wielders of the magic of cryptography must remember their secret words, else, they cannot conjure the movement of Bitcoins.

**📖 TL;DR - Too Long, Didn't Read**

Users create incomplete backups and do not realize it until it is too late.

**🌟 Specification, Scope, and Features**

Emphasize the critical nature of the password/13th word and provide an obvious way for users to opt out of it during wallet creation.

**⚔️ Motivation**

Losing your coins is the worst UX.  

**📜 Rationale**
  
There is a tradeoff between password strength and password memorability:  The more secure the password is, the harder it is for a human to remember.  This is why the BIP39 word list is used for creating seeds with sufficient randomness that can be remembered easily.  Users of passwords are unlikely to choose one that is secure enough to provide them a marginal security benefit, and secure passwords are likely to be forgotten.

**🌌 Backward Compatibility**

The seed format is unchanged.

**📚 Reference Implementation (optional)**

https://github.com/zkSNACKs/WalletWasabi/issues/9756
https://github.com/zkSNACKs/WalletWasabi/issues/10321
https://github.com/zkSNACKs/WalletWasabi/issues/10408

**🫂 Team involvement:** 

UI, UX

**✅ Subtasks:**

- [ ] Make the 13th word warning even warnier:  
>**Extend recovery seed phrase with 13th word**
>Choose a password for your wallet to add as the 13th word for your recovery seed phrase. Passwords cannot be reset if they are forgotten. If you lose your password, you will not be able to recover your wallet or spend your Bitcoin.
~~- [ ] Provide a more obvious way to opt out of choosing a password: https://github.com/zkSNACKs/WalletWasabi/issues/10661#issue-1704095588~~

**Comment by Kruwed** [comment]
A warrior has lit the beacon for help:

![image](https://github.com/molnard/The-release-game-v2-0-4-1/assets/118238055/419eeb70-1be6-47cf-a3e8-ab9f15208288)

**Comment by molnard** [comment]
Noble Author,

Your Quest has been selected for further progress! The devil is in the details - so you need to elaborate and show your quest is not evil. We only embrace quests that are leading us to the light! To prove that you will need to add the following Sections to the Quest description above: 

**⚠️ Sections to add to the Quest descriptions**

- Team involvement: [ui / code / integrations / marketing ] can be one or more. 
- Subtasks. Try to break it down as much as possible. Think about teams and jobs that can be done in parallel. Phrase it like a Todo list with elements. If something is not clear yet do not forget to add a task - "research this or that"... 

**ℹ️ Tips** 

- Try to break down the task to Teams and then to Subtasks. 
- Try to be as detailed as possible. 
- Do your best to estimate or to get an estimation from the right ppl. 
If required you can arrange a meeting and invite team leaders or ppl you believe could be involved or have something to add. 

🕐  Please make this the utmost importance - we do not have much time left!

**Comment by Kruwed** [comment]
Team involvement: UI, UX
Subtasks:

- [ ] Make the 13th word warning even warnier:  
>**Extend recovery seed phrase with 13th word**
>Choose a password for your wallet to add as the 13th word for your recovery seed phrase. Passwords cannot be reset if they are forgotten. If you lose your password, you will not be able to recover your wallet or spend your Bitcoin.
- [ ] Provide a more obvious way to opt out of choosing a password: https://github.com/zkSNACKs/WalletWasabi/issues/10661#issue-1704095588

**Comment by molnard** [comment]
Awesome, pls add it to the description itself below the existing text.

**Comment by Kruwed** [comment]
During the council meeting, we decided on following the path of subquest 1, "Make the 13th word warning even warnier".  There was no verbal opposition to subquest 2, but the journey is tiresome, so the armies will be kept in the realm of rewording.
