### ISSUE TITLE
Loading Brains with CoinJoin@norbo

### ISSUE THREAD

**Issue by molnard** [molnard/The-release-game-v2-0-4-1#6]
**📜 Preamble**

Loading Brains with CoinJoin by @molnard

**📖 TL;DR - Too Long, Didn't Read**

The screen that everyone gazes 👀 a lot - the loading screen. However, the time spent on this screen is reduced by speeding up the wallet load, but it is still one of the best places to deliver information to the user because he/she is waiting to get into the wallet and take some action. The loading screen should highlight important aspects of CoinJoin. 

**🌟 Specification, Scope, and Features**

- Scope: replace the loading screen graphics and text. Do not touch the progress bar!
- Find 3-8 facts about CoinJoin or Wasabi that will incentive people to use CoinJoin, like:
  - Display statistical information. Show how many CJs we did or how much we mixed - improve trust in the product. 
  - Elaborate on fees - show that it is the cheapest solution. 
  - Let auto coinjoin do the job - incentivize to use it - only if it is not turned on! 
  - Let Wasabi run  - make the user aware that it will only mix if it is running. 
  - Talk about privacy profile - emphasize the privacy profile.

**⚔️ Motivation**

We have two very important motivation:
- Bring privacy to Bitcoin by default. 
- CoinJoin is our source of income. Kind of making the first point possible. 

It is our product that we "sell" and we are the best in it on planet earth. We can be proud and bold about it - we can be. Show and talk about our successes. 

**📜 Rationale**

Implementation starts on the desk of us and community, what would be the best "Tip of the Day" or "Fact" about coinjoin. We can also check the past what was the most interesting information on social media so far and base the idea on that. The bests selected and then the graphical designer create an art for the text. After that it is implemented in the software. I suggest having static vector pictures that can be rotated like a slideshow (5 secs) on the loading screen instead of fancy and complex vector animation. Every wallet load starts with a random picture. 

Also static pictures will use fewer resources. 

No privacy implication. 

**🌌 Backward Compatibility**

No compatibility issue. The code will be cleaner - right now the animation is coded manually in C#. That will be gone. 

**📚 Reference Implementation (optional)**

![loadingscreen](https://github.com/molnard/The-release-game-v2-0-4-1/assets/9844978/5d791ad7-6bc6-40b9-9d46-e779df38d203)

- https://github.com/zkSNACKs/WalletWasabi/issues/9751
- https://github.com/zkSNACKs/WalletWasabi/issues/11173

**👥 Team involvements** 

- Lead: @Canorbo
- Graphical design: @Bodnaralexa
- Brains: @Canorbo, @adamPetho, @Bodnaralexa, @molnard, @Kruw
- Statistical data miner: @Szpoti
- Implementation
  - Code team: @adamPetho 
  - Ui: @SuperJmn

**💪 Subtask**
- [ ] Figure out the topics, and write 14 sentences about what to display. @Canorbo 🕐 4 days
  - What features to highlight?
  - Features on the Website can be. 
  - Examples to show (Promotion is on the focus - not education!): 
    - Incentivize CoinJoin - talk about the privacy guarantees of CJ. 
    - Auto CoinJoin - Turn ON! Do not scare the users. 
    - CoinJoin profiles. 3 different slides? 
    - Statistical information about CJ. How many CoinJoins happened until 2023?
    - Biggest CoinJoin number of input-output.
    - How many BTCs were mixed so far? 
    - Privacy suggestions
    - OneHop (friends don't pay)
    - Free remix (network fee, not zero), mentioned with CJ fees
    - Speed up tx
    - Cancel transaction
    - Join our Telegram community. Direct mention of the telegram group link. No clickable link! 
    - Join our Instagram community. Direct mention of the telegram group link. No clickable link!  
    - Promote docs!
  - No-go (do not highlight): CTRL-C-D, Coin control, Blacklisting
- [ ]  Graphical design. Still pictures. @Bodnaralexa 🕐 3 weeks
  - Start with sketches and reach a consensus (ping-pong).  
  - Screenshots from the software. 
  - Coordinate with the UI team to ensure consistent design. 
  - Draw SVG-s. Ask @SuperJmn what is the best format.
- [ ] Implementation @adamPetho 🕐 2 weeks
  - Coordinate with @SuperJmn for the best solution
  - Slideshow engine 
  - Random
  - Auto slideshow AND prev next button

**Comment by molnard** [comment]
Noble Author,

Your Quest has been selected for further progress! The devil is in the details - so you need to elaborate and show your quest is not evil. We only embrace quests that are leading us to the light! To prove that you will need to add the following Sections to the Quest description above: 

**⚠️ Sections to add to the Quest descriptions**

- Team involvement: [ui / code / integrations / marketing ] can be one or more. 
- Subtasks. Try to break it down as much as possible. Think about teams and jobs that can be done in parallel. Phrase it like a Todo list with elements. If something is not clear yet do not forget to add a task - "research this or that"... 

**ℹ️ Tips** 

- Try to break down the task to Teams and then to Subtasks. 
- Try to be as detailed as possible. 
- Do your best to estimate or to get an estimation from the right ppl. 
If required you can arrange a meeting and invite team leaders or ppl you believe could be involved or have something to add. 

🕐  Please make this the utmost importance - we do not have much time left!
